export enum INVOICES_ACTION_TYPES {
  FETCH_INVOICES_START = "invoices/FETCH_INVOICES_START",
  FETCH_INVOICES_SUCCESS = "invoices/FETCH_INVOICES_SUCCESS",
  FETCH_INVOICES_FAILED = "invoices/FETCH_INVOICES_FAILED",
  CLEAR_INVOICES = "invoices/CLEAR_INVOICES",
}
