// const {
//   REACT_APP_API_KEY: APIKEY,
//   REACT_APP_AUTH_DOMAIN: AUTHDOMAIN,
//   REACT_APP_PROJECT_ID: PROJECTID,
//   REACT_APP_STORAGE_BUCKET: STORAGEBUCKET,
//   REACT_APP_MESSAGING_SENDER_ID: MESSAGINGSENDERID,
//   REACT_APP_ID: APPID,
//   REACT_APP_DATABASE_URL: DATABASEURL,
// } = import.meta.env;

// export {
//   APIKEY,
//   AUTHDOMAIN,
//   PROJECTID,
//   STORAGEBUCKET,
//   MESSAGINGSENDERID,
//   APPID,
//   DATABASEURL,
// };
// const {
//   REACT_APP_API_KEY,
//   REACT_APP_AUTH_DOMAIN,
//   REACT_APP_PROJECT_ID,
//   REACT_APP_STORAGE_BUCKET,
//   REACT_APP_MESSAGING_SENDER_ID,
//   REACT_APP_ID,
//   REACT_APP_DATABASE_URL,
// } = import.meta.env;

// export {
//   REACT_APP_API_KEY,
//   REACT_APP_AUTH_DOMAIN,
//   REACT_APP_PROJECT_ID,
//   REACT_APP_STORAGE_BUCKET,
//   REACT_APP_MESSAGING_SENDER_ID,
//   REACT_APP_ID,
//   REACT_APP_DATABASE_URL,
// };
